### ISSUE TITLE
Does it support android?

### ISSUE THREAD

**Issue by iosephmagno** [cosee/native_image_cropper#8]
Does the plugin support android?
I get this error
```
I/flutter (14368): MissingPluginException(No implementation found for method cropRect on channel biz.cosee/native_image_cropper_android)
I/flutter (14368): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
I/flutter (14368): <asynchronous suspension>
I/flutter (14368): #1      NativeImageCropperAndroid.cropRect (package:native_image_cropper_android/src/platform.dart:33:11)
I/flutter (14368): <asynchronous suspension>
```

**Comment by quoc-huynh-cosee** [comment]
It should support android. Can you give me a miminal example of your code?

**Comment by quoc-huynh-cosee** [comment]
I will close the issue now. If you still have trouble with android devices, feel free to reopen it.
